[package]
name = "kernel"
version = "0.0.1"
edition = "2021"

[dependencies]
spin = "0.9.8"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
acpi = "5.0.0"
log = "0.4.20"
aml = "0.16.4"
uefi = { version = "0.26.0" }
uefi-services = { version = "0.23.0" }



